"""Initial migration

Revision ID: c1ce2c61ab93
Revises: 
Create Date: 2024-08-15 20:35:24.327055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1ce2c61ab93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('register')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_photo', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('date_of_birth', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('additional_details', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('additional_details')
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('profile_photo')

    op.create_table('register',
    sa.Column('UserName', sa.VARCHAR(length=50), nullable=False),
    sa.Column('eMAil', sa.VARCHAR(length=50), nullable=False),
    sa.Column('PassWord', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('UserName')
    )
    # ### end Alembic commands ###
